In [2]:
import numpy as np
from scipy import sparse
import matplotlib.pyplot as plt

from IPython.display import display
from IPython.display import Latex

## 1.1 Vectors

The simplest data structure representing a vector: `list`

In [3]:
x = [-1.1, 0.0, 3.6, -7.2]
len(x)

4

Here `y` is a `tuple` consisting of two scalars. It is neither a `list` nor a `vector`.

In [4]:
y = (1,2)

Another common way to represent vectors in Python is to use a `numpy array`

In [5]:
x = np.array([-1.1,0.0,3.6,-7.2])
len(x)

4

#### Indexing

In [6]:
x = np.array([-1.1, 0.0, 3.6, -7.2])
print('vector "x:"', x)

vector "x:" [-1.1  0.   3.6 -7.2]


0-based indexing

In [7]:
x[0]

-1.1

Assign 4 to $x_3$

In [8]:
x[2] = 4
print('vector "x":', x)

vector "x": [-1.1  0.   4.  -7.2]


The negative integer index is counted from the end of the vector

In [9]:
x[-1] == x[3]

True

In [10]:
x[-2] == x[2]

True

#### Assignment versus copying

x =y

The assignment expression gives a new name (or reference) y to the same array that is already referenced by x instead of creating a copy of x.

The behavior in Python is same as Julia, different from MatLab / Octave

In [11]:
x = np.array([-1.1, 0.0, 3.6, -7.2])
y = x 
x[2] = 20.0
print(y)

[-1.1  0.  20.  -7.2]


Use the method `copy` to get a copy of the array

In [12]:
x = np.array([-1.1, 0.0, 3.6, -7.2])
y = x.copy()
x[2] = 20.0
print(y)
print(x)

[-1.1  0.   3.6 -7.2]
[-1.1  0.  20.  -7.2]


#### Vector equality

Equality of vectors is checked using the relational operator == (double equal signs).

The Python expression evaluates to `True` if the expression on the left and right-hand side of the relational operator is equal, and to `False` otherwise.

List:

In [13]:
x = [-1.1, 0.0, 3.6, -7.2]
y = x.copy()
x == y

True

In [14]:
x = [-1.1, 0.0, 3.6, -7.2]
y = x.copy()
y[3] = 9.0
x == y

False

In [15]:
x = np.array([-1.1, 0.0,3.6,-7.2])
y = x.copy()
y[2] = 4.0
# y == x
# Relational operators in Julia check the entire vector to determine a single boolean expression
# Relational operators in Python check each individual vector value
z=x.copy()
z[1] = 4.0
x[1] = 4.0
y == x, z == x

(array([ True, False, False,  True]), array([ True,  True,  True,  True]))

In [16]:
x = np.array([1.3])
y = 1.3
x,y, x ==y, x[0]==y, type(x)==type(y)
#Different from Julia: the third result would be false because they're different types (array and int), just like the 5th result the fourth result is the same, barring 0,1 indexing differences

(array([1.3]), 1.3, array([ True]), True, False)

#### Block or stacked vectors

In [17]:
#In Julia you concatenate vectors using semicolon or vcat: [x;y] or vcat(x,y)
#In Python you can use:
x = np.array([1,2]); y = np.array([1,1,0]);
z = np.concatenate((x,y))
z

array([1, 2, 1, 1, 0])

#### Subvectors and Slicing

In [18]:
x = np.array([9,4,3,0,5])
y = x[1:4] #slicing in python is [inclusive:exclusive], in Julia:[inclusive:inclusive]
y

array([4, 3, 0])

In [19]:
x[3:5] = [-2,-3] #would be x[4:5] in Julia as though Julia says: items i through j; Python says: from item i to item j
x

array([ 9,  4,  3, -2, -3])

In [72]:
#In Julia a reverse slice is: [end:-1:1] ie [start:increment:end]
#In Python a reverse slice is: [::-1] ie [start:end:increment]
x, x[4:1:-1] #would be: x[3:-1:2]

(array([ 9,  4,  3, -2, -3]), array([-3, -2,  3]))

#### Vector of First Differences